[build]
  command = "npm install -g pnpm@9.12.1 && pnpm install && pnpm build"
  publish = "dist"
  environment = { NODE_VERSION = "21.7.3", PNPM_VERSION = "9.12.1" }

[build.environment]
  NODE_VERSION = "21.7.3"
  PNPM_VERSION = "9.12.1"

[caches]
  node_modules = false
